### PR TITLE
User login

### PR DESCRIPTION
**Pull request by AC159**
Users are now able to register and login with google and with email and password

Tests are implemented for the UI and unit tests for the corresponding view models

To do before merging:
- Verify that you can login with google and with email and password
- Verify that input field validation works properly

### CODE REVIEW

**Comment by BunnyPrince** [comment]
Everything works correctly on my end

**Review by BunnyPrince — APPROVED** [review]
looks good

**Review by Zain-MKhan — APPROVED** [review]
Login with google and email works
Input field validation works properly

**Review by DrakeHunterK7 — APPROVED** [review]
Everything looks good!

Improvements for future versions:
- Adding underscores and punctuation as special characters in password creation
- Displaying error messages when entering the wrong email/password

**Pull request merged**
